"""Patch document — code fix generated by the Program Repair Agent."""

from enum import StrEnum

from beanie import PydanticObjectId
from pydantic import Field

from app.models.base import BaseDocument


class PatchStrategy(StrEnum):
    """Strategy used to generate the patch."""

    MINIMAL = "minimal"
    SAFE = "safe"
    REFACTOR = "refactor"
    TEMPLATE_BASED = "template_based"
    LLM_GENERATED = "llm_generated"


class PatchStatus(StrEnum):
    CANDIDATE = "candidate"
    VALIDATING = "validating"
    ACCEPTED = "accepted"
    REJECTED = "rejected"


class Patch(BaseDocument):
    """A code patch generated by the Program Repair Agent.

    Multiple candidate patches may be generated per bug. Only patches
    that pass validation are accepted.
    """

    project_id: PydanticObjectId
    bug_report_id: PydanticObjectId
    strategy: PatchStrategy
    status: PatchStatus = Field(default=PatchStatus.CANDIDATE)
    diff: str = Field(description="Unified diff of the patch")
    file_path: str = ""
    description: str = ""
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    rejection_reason: str = ""

    class Settings:
        name = "patches"
        use_state_management = True
        indexes = [
            "project_id",
            "bug_report_id",
        ]
